name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    # Add this environment variable to satisfy the Node 24 requirement
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://huggingface.co/spaces/FassiUrRehman/proview-api main